apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  clusterIP: 100.67.115.90
  ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    app: mysql-database
  type: ClusterIP
