apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fortify-storage-class
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2 
  zone: eu-west-2a
  iopsPerGB: "10"
reclaimPolicy: Retain
