name: Run tests

description: 'provision dependencies and test service'
inputs:
  working-directory:
    description: 'working directory to run commands'
    required: true
    default: '.'

runs:
  using: "composite"
  steps:
    - name: provision Go
      uses: actions/setup-go@v3
      with:
        go-version-file: "${{ inputs.working-directory }}/go.mod"
    - run: |
        cd ${{ inputs.working-directory }}
        go version
      shell: bash

    - name: provision just 
      uses: taiki-e/install-action@just
      with:
        just-version: latest

    - name: generate .env file
      run: |
        cd ${{ inputs.working-directory }}
        just gen-dotenv test
      shell: bash

    - name: run tests
      run: | 
        cd ${{ inputs.working-directory }}
        just test
      shell: bash
