services:
  generator:
    build: 
      context: services/generator
      args:
        # ENV_FILE: services/generator/configuration/it
        ENV_FILE: it
    container_name: generator
    ports:
      - "8080:8080"

  fortify:
    build:
      context: services/fortify
      args:
        ENV_FILE: it-fortify
    container_name: fortify
    ports:
      - "9002:9002"
    depends_on:
      mysql:
        condition: service_healthy
    restart: on-failure

  mysql:
    image: mysql:lts 
    env_file: services/fortify/configuration/it-mysql
    container_name: mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -p$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 10s
      retries: 5
