services:
  generator:
    build: services/generator
    container_name: generator
    env_file: configuration/environments/test-generator-env
    ports:
      - "8080:8080"

  fortify:
    build: services/fortify
    container_name: fortify
    env_file: configuration/environments/test-fortify-env
    ports:
      - "9002:9002"
    depends_on:
      mysql:
        condition: service_healthy
    restart: on-failure

  mysql:
    image: mysql:lts 
    env_file: configuration/environments/test-mysql-env
    container_name: mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -p$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 10s
      retries: 5
