services:
  fortify:
    build: .
    env_file: .env
    container_name: fortify
    ports:
      - "9002:9002"
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure

  db:
    image: mysql:lts 
    env_file: db-env
    container_name: mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -p$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 10s
      retries: 5
