FROM golang:latest AS BUILD_IMAGE

WORKDIR /src/app
COPY . .

RUN go mod download && go mod verify

RUN CGO_ENABLED=0 GOOS=linux go build -v -o /usr/local/bin/fortify cmd/fortify/main.go

FROM alpine:latest

ARG GIN_MODE=debug
ARG PORT=9002
ARG GENERATOR_URL=http://localhost:8080
ARG DB_USER=fortifyUser
ARG DB_HOST=localhost
ARG DB_PASSWORD=fortifyPassword

ENV GIN_MODE=$GIN_MODE
ENV PORT=$PORT
ENV GENERATOR_URL=$GENERATOR_URL
ENV DB_USER=$DB_USER
ENV DB_HOST=$DB_HOST
ENV DB_PASSWORD=$DB_PASSWORD

WORKDIR /fortify

COPY --from=BUILD_IMAGE /usr/local/bin/fortify /fortify
COPY static /fortify/static
COPY templates /fortify/templates

RUN chmod +x fortify

EXPOSE $PORT

CMD [ "./fortify" ]
