FROM golang:latest AS BUILD_IMAGE

WORKDIR /src/app
COPY . .

RUN go mod download && go mod verify
RUN CGO_ENABLED=0 GOOS=linux go build -v -o /src/app/bin/fortify cmd/fortify/main.go

FROM alpine:latest

ARG ENV_FILE=test

ENV ENV_FILE=$ENV_FILE
ENV PORT=9002

WORKDIR /app

COPY --from=BUILD_IMAGE /src/app/bin/fortify /app/bin/fortify
COPY setup.sh /app/setup.sh
COPY configuration/$ENV_FILE /app/configuration/$ENV_FILE 
COPY static /app/static
COPY templates /app/templates

# RUN chmod +x fortify

EXPOSE $PORT

ENTRYPOINT sh setup.sh $ENV_FILE ./bin/fortify
