set dotenv-load 

default:
	just --list

# Run test suite in verbose mode with the gin server mode set to test
test $GIN_MODE="test":
	go test ./... -v

# Run fortify in a docker container
run:
	go run ./...

# Build the docker image for fortify and mysql
build:
	go build -v -o bin/fortify cmd/fortify/main.go

# Run the build. pass in a paramater to set the gin server mode. default is debug
run-build $GIN_MODE="debug":
	./bin/app

# Run fortify in a docker container
run-container:
	docker-compose down
	docker-compose up

# Build the docker image for fortify and mysql
build-image:
	docker-compose build

# Run linter
lint:
	golangci-lint run ./... --verbose

# Generate a .env file
[no-cd]
gen-dotenv mode="debug" port="9002" generator-url="http://localhost:8080" db-user="fortifyUser" db-host="mysql" db-password="fortifyPassword":
	touch .env
	echo "GIN_MODE=\"{{mode}}\"" >> .env
	echo "PORT=\"{{port}}\"" >> .env
	echo "GENERATOR_URL=\"{{generator-url}}\"" >> .env
	echo "DB_USER=\"{{db-user}}\"" >> .env
	echo "DB_HOST=\"{{db-host}}\"" >> .env
	echo "DB_PASSWORD=\"{{db-password}}\"" >> .env
