name: Build Service

description: 'Build Go services'

runs:
  using: "composite"
  steps:
    - name: provision Go
      uses: actions/setup-go@v3
      with:
        go-version-file: 'go.mod'
    - run: go version
      shell: bash

    - name: provision just 
      uses: taiki-e/install-action@just
      with:
        just-version: latest

    - name: build service
      run: just build
      shell: bash
