FROM golang:latest AS BUILD_IMAGE

WORKDIR /src/app
COPY . .

RUN go mod download && go mod verify
RUN CGO_ENABLED=0 GOOS=linux go build -v -o /src/app/bin/generator cmd/generator/main.go
FROM alpine:latest

ARG ENV_FILE=test

ENV ENV_FILE=$ENV_FILE
ENV PORT=8080

WORKDIR /app

COPY --from=BUILD_IMAGE /src/app/bin/generator /app/bin/generator
COPY setup.sh /app/setup.sh
COPY configuration/$ENV_FILE /app/configuration/$ENV_FILE

EXPOSE $PORT


ENTRYPOINT sh setup.sh $ENV_FILE ./bin/generator
