set dotenv-load 

alias rb := run-build
alias b := build
alias t := test
alias r := run
alias l := lint

default:
	just --list

# Run test suite in verbose mode with the gin server mode set to test
test $GIN_MODE="test":
	go test ./... -v

run:
	go run ./...

# Build the bin and place it at the relative path of bin/app
build:
	go build -v -o bin/generator cmd/generator/main.go

# Run the build. pass in a paramater to set the gin server mode. default is debug
run-build $GIN_MODE="debug":
	./bin/generator

# Run linter
lint:
	golangci-lint run ./... --verbose

# Build the docker image
build-image env_file="test":
	docker build --build-arg="ENV_FILE={{env_file}}" -t generator .

run-container port="8080":
	docker run -p {{port}}:{{port}} generator:latest
 
# Generate a .env file
gen-dotenv mode="debug" port="8080" min="7" max="25":
	touch .env
	echo "GIN_MODE=\"{{mode}}\"" >> .env
	echo "PORT=\"{{port}}\"" >> .env
	echo "STRING_MIN=\"{{min}}\"" >> .env
	echo "STRING_MAX=\"{{max}}"\" >> .env
