name: Run golangci-lint

description: 'Runs golangci-lint on source code'
inputs:
  working-directory:
    description: 'working directory to run commands'
    required: true
    default: '.'

runs:
  using: "composite"
  steps:
    - name: provision Go
      uses: actions/setup-go@v4
      with:
        go-version-file: "${{ inputs.working-directory }}/go.mod"

    - name: provision just 
      uses: taiki-e/install-action@just
      with:
        just-version: latest

    - name: provision golangci-lint
      run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin
      shell: bash

    - name: golangci-lint version 
      run: |
        cd ${{ inputs.working-directory }}
        golangci-lint -v
      shell: bash


    - name: run golangci-lint
      run: |
        cd ${{ inputs.working-directory }}
        just lint
      shell: bash
