name: Fortify QA Test

on:
  push:
    branches: [ main ]
    paths:
      - 'services/fortify/**'
    workflow_dispatch:

permissions:
  contents: read

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: run tests
        uses: ./actions/test-go
        with:
          working-directory: ./services/fortify

  static-analysis-test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2
        with:
          working-directory: ./services/fortify

      - name: run linter
        uses: ./actions/lint-go
        with:
          working-directory: ./services/fortify

  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2
        with:
          working-directory: ./services/fortify

      - name: build service
        uses: ./actions/build-go
        with:
          working-directory: ./services/fortify
