name: Test Service

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run_tests:
    name: run tests
    runs-on: ubuntu-latest
    steps:
    - uses: action/checkout@v3

    - name: provision Go
      uses: action/setup-go@v3
      with:
        go-version: 1.18

    - name: provision just 
      uses: extractions/setup-just@v1
      with:
        just-version: latest


    - name: run unit tests
      run: just test
