name: Test action from actions repo

on:
  push:
    branches: [ main ]
    workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: run tests
        uses: BrandonC98/passMan-infra/run-tests-actions@main
