name: Test Service

on:
  push:
    branches: [ mainOFF ]
  workflow_dispatch:

jobs:
  run_tests:
    name: run tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: provision Go
      uses: actions/setup-go@v3

    - name: provision just 
      uses: taiki-e/install-action@just
      with:
        just-version: latest


    - name: create .env file
      run: just gen-dotenv test

    - name: run unit tests
      run: just test
